### ISSUE TITLE
[ERROR] decryptData() missing 1 required positional argument: 'verbose'

### ISSUE THREAD

**Issue by kresbayyy** [noaione/yuu#1]
> [ERROR] Problem occured
> reason: decryptData() missing 1 required positional argument: 'verbose'

Please fix ~~akmj~~

![](https://puu.sh/CzXED/df6ccc0be8.png)

**Comment by noaione** [comment]
Will be fixed soon enough, including one more error in `mergeVideo()`

And also fixing one verbose leak in normal mode

**Comment by noaione** [comment]
Fixed in 1717c9b.

**Comment by noaione** [comment]
Okay, i forget to put one more line of code
