### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by josandos** [noaione/yuu#2]
> yuu -v  https://abema.tv/video/episode/54-25_s1_p1
> [INFO] Starting yuu...
> [DEBUG] Using proxy mode: No proxy
> [INFO] Parsing website
> [DEBUG] Requesting pages
> [DEBUG] Pages requested
> [DEBUG] Parsing webpage
> Traceback (most recent call last):
>   File "/usr/local/bin/yuu", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/yuu/command.py", line 69, in main
>     dltitle, eptitle, m3u8link = webparse(args.input, args.res, sesi, args.verbose)
>   File "/usr/local/lib/python3.7/site-packages/yuu/parser.py", line 172, in webparse
>     title = soup.find('span', attrs={'class': 'abm_cq_m abm_cq_l abm_cq_c'}).text
> AttributeError: 'NoneType' object has no attribute 'text'

I'm using a Japanese VPN with this.

**Comment by noaione** [comment]
Yeah, Abema changed something on the website, so currently I'm rewriting the parser to use the API

**Comment by noaione** [comment]
Fixed on version `0.1.4` update it using `pip install yuu==0.1.4 -U`
