### ISSUE TITLE
Invalid URL - No schema supplied

### ISSUE THREAD

**Issue by tako777** [noaione/yuu#21]
Your software used to work flawlessly about a week ago, congrats for that. But now when I try to continue downloading from AbemaTV it keeps throwing this error. I wonder if maybe they changed something...

> ERROR] Problem occured
> reason: Invalid URL '/tsvpg/90-995_s13_p1/h264/1080/6Spwr8Srf3WmKDHo6yxxUJfaW81n
> qGYsB.ts?tver=5kgSyz': No schema supplied. Perhaps you meant http:///tsvpg/90-99
> 5_s13_p1/h264/1080/6Spwr8Srf3WmKDHo6yxxUJfaW81nqGYsB.ts?tver=5kgSyz?

![sc](https://user-images.githubusercontent.com/57922506/69099721-73be2700-0a29-11ea-8822-bdb47c7ddf8b.PNG)

**Comment by noaione** [comment]
I guess they changed something, I'll look around it later

**Comment by noaione** [comment]
Fixed, update to version `1.1.1`

**Comment by tako777** [comment]
Great, you rock!
