### ISSUE TITLE
cannot download premium video

### ISSUE THREAD

**Issue by Campanula26** [noaione/yuu#8]
some video is available free for one week, but this video cannot be downloaded

**Comment by noaione** [comment]
Can you give me an example?

**Comment by Campanula26** [comment]
https://abema.tv/video/episode/90-493_s0_p1131
for example

**Comment by Campanula26** [comment]
yuu download https://abema.tv/video/episode/90-493_s0_p1131
[INFO] Starting yuu v0.2.0...
[INFO] Fetching user token
[INFO] Parsing webpage
[INFO] Parsing m3u8
[ERROR] Cannot download a premium video.

**Comment by noaione** [comment]
Are you using Japanese proxy or not? It can be 403 error if you're outside Japan.
